version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=development-postgres.postgres.database.azure.com
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=BG]j2s29e8|H
      - DB_NAME=postgres
      - DB_SSL=true
      - DB_SSL_REJECT_UNAUTHORIZED=false
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=kutum_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
